services:
  api:
    build: .
    ports:
      - "8030:8000"
    volumes:
      - shared-data:/shared-data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      default:
        aliases:
          - splat-highlight-pilot-api
      splat-highlight-pilot-net:
        aliases:
          - splat-highlight-pilot-api

volumes:
  shared-data:
    name: shared-data

networks:
  default:
  splat-highlight-pilot-net:
    name: splat-highlight-pilot-net
