services:
  api:
    build: .
    ports:
      - "8030:8000"
    volumes:
      - shared-data:/shared-data
    env_file:
      - .env
    restart: unless-stopped

volumes:
  shared-data:
    external: true
